root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/zabdoc"
  bin = "tmp/server"
  full_bin = "PORT=8080 tmp/server"
  include_ext = ["go"]
  include_dir = ["internal", "cmd"]
  exclude_dir = [".idea", "worker"]
  exclude_file = []
  delay = 1000
  
