<script lang="ts">
    import SEO from "$lib/components/seo.svelte";
</script>

<SEO
    title="Terms of Use | zabdoc"
    description="Terms of Use for zabdoc, an independent tool for SZABIST students. Learn about proper usage and responsibilities."
    canonical="https://zabdoc.xyz/terms"
    url="https://zabdoc.xyz/terms"
/>

<div class="mx-auto space-y-8">
    <div class="prose prose-neutral dark:prose-invert prose-headings:font-black prose-headings:uppercase prose-headings:tracking-tight prose-a:text-primary prose-a:font-bold prose-strong:font-black max-w-none">
        <h1>Terms of Use</h1>

        <p class="text-lg">
            These terms govern your use of <strong>zabdoc</strong> (the "Service"). By accessing and using
            zabdoc, you agree to be bound by these terms. If you do not agree with any part of these terms,
            please do not use the Service.
        </p>

        <h2>1. Educational Purpose</h2>

        <p>
            This tool is provided <strong>for educational and convenience purposes only</strong>. It is designed
            to assist SZABIST students with document generation and data retrieval. Any use outside of educational
            context is at your own risk.
        </p>

        <h2>2. User Responsibilities</h2>

        <p>You are solely responsible for:</p>
        <ul>
            <li>Ensuring the accuracy of all information you enter into the system</li>
            <li>Verifying that generated documents meet your institution's submission requirements</li>
            <li>Using the tool in compliance with SZABIST policies and local laws</li>
            <li>Maintaining the confidentiality of your ZabDesk credentials</li>
            <li>Reporting any errors or discrepancies to your instructors</li>
        </ul>

        <h2>3. ZabDesk Credentials</h2>

        <p>
            <strong>Critical:</strong> You must only use your own ZabDesk credentials or credentials you are
            explicitly authorized to use. Unauthorized access to others' accounts is:
        </p>
        <ul>
            <li>A violation of these terms</li>
            <li>Potentially illegal under computer fraud laws</li>
            <li>Subject to disciplinary action by SZABIST</li>
            <li>Grounds for immediate termination of your access to this Service</li>
        </ul>

        <p>
            zabdoc cannot and will not be held liable for unauthorized access or misuse of credentials.
        </p>

        <h2>4. Generated Documents</h2>

        <p>
            The PDFs generated by zabdoc are intended for academic submission only. You agree to:
        </p>
        <ul>
            <li>Use generated documents only for legitimate educational purposes</li>
            <li>Ensure the documents comply with SZABIST's submission guidelines and standards</li>
            <li>Submit accurate information and not use the tool to generate false documentation</li>
            <li>Accept full responsibility for the content and accuracy of submitted documents</li>
            <li>Not represent the tool or its output as officially endorsed by SZABIST</li>
        </ul>

        <p>
            zabdoc is an independent tool and is not responsible for any issues arising from document submission.
        </p>

        <h2>5. Service Availability</h2>

        <p>
            We make no guarantee regarding:
        </p>
        <ul>
            <li>Continuous availability of the Service</li>
            <li>Uninterrupted functionality of the tool</li>
            <li>Compatibility with future versions of ZabDesk</li>
            <li>Support for all courses or classes offered at SZABIST</li>
        </ul>

        <p>
            The scraping feature depends on ZabDesk's availability and compatibility. Changes to ZabDesk's
            structure or authentication may temporarily or permanently affect the scraper's functionality.
        </p>

        <h2>6. No Warranty</h2>

        <p>
            <strong>DISCLAIMER:</strong> This Service is provided "AS IS" without any warranties, express or implied.
            We disclaim all warranties including, without limitation:
        </p>
        <ul>
            <li>Merchantability</li>
            <li>Fitness for a particular purpose</li>
            <li>Non-infringement of third-party rights</li>
            <li>Accuracy, completeness, or timeliness of information</li>
        </ul>

        <p>
            Use of this Service is entirely at your own risk and discretion. You assume all responsibility and
            risk for any damages or losses resulting from your use of the tool.
        </p>

        <h2>7. Limitation of Liability</h2>

        <p>
            In no event shall zabdoc, its developers, or contributors be liable for any indirect, incidental, special,
            consequential, or punitive damages, including but not limited to:
        </p>
        <ul>
            <li>Lost grades or academic consequences</li>
            <li>Data loss or corruption</li>
            <li>Business interruption</li>
            <li>Any other loss of use, data, or profits</li>
        </ul>

        <p>
            Even if advised of the possibility of such damages. This limitation applies to all claims, whether based
            on warranty, contract, tort, strict liability, or any other legal theory.
        </p>

        <h2>8. Prohibited Uses</h2>

        <p>You agree not to:</p>
        <ul>
            <li>Use the tool to generate false or fraudulent documents</li>
            <li>Attempt to gain unauthorized access to ZabDesk or bypass its security measures</li>
            <li>Access the service using others' credentials without permission</li>
            <li>Engage in any form of harassment, abuse, or illegal activity</li>
            <li>Use the tool for commercial purposes without explicit permission</li>
            <li>Share or distribute credentials through the service</li>
            <li>Overload or attack the servers with excessive requests</li>
        </ul>

        <h2>9. Termination of Access</h2>

        <p>
            We reserve the right to terminate or restrict your access to zabdoc at any time without notice if we
            determine that you have violated these terms or engaged in prohibited conduct. Termination is effective
            immediately upon notice.
        </p>

        <h2>10. Intellectual Property</h2>

        <p>
            zabdoc is released under the <a href="https://www.gnu.org/licenses/gpl-3.0.html" target="_blank" rel="noreferrer">GNU General Public License v3.0</a>. The source code
            is open and available on <a href="https://github.com/hammadmajid/zabdoc" target="_blank" rel="noreferrer">GitHub</a>. You may use, modify, and distribute
            the software in accordance with the GPL-3.0 license terms.
        </p>

        <h2>11. Third-Party Services</h2>

        <p>
            zabdoc integrates with ZabDesk and SZABIST systems. We are not responsible for:
        </p>
        <ul>
            <li>Third-party service outages or changes</li>
            <li>Data accuracy of information retrieved from ZabDesk</li>
            <li>SZABIST's policies or requirements</li>
            <li>Changes to external systems that affect our functionality</li>
        </ul>

        <h2>12. Modification of Terms</h2>

        <p>
            We may modify these terms at any time. Changes take effect immediately upon posting to this page.
            Your continued use of the Service constitutes acceptance of any modified terms.
        </p>

        <h2>13. Governing Law</h2>

        <p>
            These terms are governed by the laws of Pakistan. By using zabdoc, you consent to the jurisdiction of
            Pakistani courts and agree to submit to their exclusive jurisdiction for any disputes arising from these terms.
        </p>

        <h2>14. Acknowledgment</h2>

        <p>
            By using zabdoc and agreeing to these terms, you acknowledge that you have read, understood, and agree to
            be bound by all of these terms and conditions. If you do not agree, do not use the Service.
        </p>

        <hr class="my-8" />

        <p class="text-sm text-muted-foreground">
            Last updated: March 2026. Questions about these terms?{" "}
            <a href="mailto:hammadmajid@pm.me" class="text-primary font-bold hover:underline">Contact us</a>.
        </p>

        <p class="text-sm text-muted-foreground">
            See also: <a href="/privacy" class="text-primary font-bold hover:underline">Privacy Policy</a> | <a href="/about" class="text-primary font-bold hover:underline">About zabdoc</a>
        </p>
    </div>
</div>
